# Generated by Django 5.1.4 on 2025-01-08 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Title')),
                ('note', models.CharField(blank=True, max_length=150, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Pill',
                'verbose_name_plural': 'Pills',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.CreateModel(
            name='TakingPill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('is_taken', models.BooleanField(default=False, verbose_name='Is taken')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='foodlog.day', verbose_name='Day')),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='foodlog.pill', verbose_name='Pill')),
            ],
            options={
                'verbose_name': 'Taking the pill',
                'verbose_name_plural': 'Taking the pills',
            },
        ),
    ]
