# Generated by Django 5.1.4 on 2025-01-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlog', '0002_pill_alter_product_options_takingpill'),
    ]

    operations = [
        migrations.AddField(
            model_name='takingpill',
            name='note',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Note'),
        ),
    ]
