# Generated by Django 5.1.4 on 2025-01-26 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodlog', '0005_product_lactose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='lactose',
            new_name='lactose_free',
        ),
    ]
