# Generated by Django 5.1.4 on 2025-01-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlog', '0007_alter_product_lactose_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lactose_free',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Lactose-free'),
        ),
    ]
